#!/bin/bash

# WARNING: to work, it needs this patch for docutils
# https://sourceforge.net/tracker/?func=detail&atid=422032&aid=1459707&group_id=38414

rst2beamer.py --stylesheet=stylesheet.latex --documentoptions=14pt pypy-vm.txt pypy-vm.latex || exit
sed 's/\\date{}/\\input{author.latex}/' -i pypy-vm.latex || exit
pdflatex pypy-vm.latex || exit

